# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import apiservice_pb2 as apiservice__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='authservice.proto',
  package='protos',
  syntax='proto3',
  serialized_options=b'Z\tauth;auth',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61uthservice.proto\x12\x06protos\x1a\x10\x61piservice.proto2\x80\x01\n\x0b\x41uthService\x12\x36\n\x05Login\x12\x14.protos.LoginRequest\x1a\x15.protos.LoginResponse\"\x00\x12\x39\n\x06Logout\x12\x15.protos.LogoutRequest\x1a\x16.protos.LogoutResponse\"\x00\x42\x0bZ\tauth;authb\x06proto3'
  ,
  dependencies=[apiservice__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_AUTHSERVICE = _descriptor.ServiceDescriptor(
  name='AuthService',
  full_name='protos.AuthService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=48,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='protos.AuthService.Login',
    index=0,
    containing_service=None,
    input_type=apiservice__pb2._LOGINREQUEST,
    output_type=apiservice__pb2._LOGINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Logout',
    full_name='protos.AuthService.Logout',
    index=1,
    containing_service=None,
    input_type=apiservice__pb2._LOGOUTREQUEST,
    output_type=apiservice__pb2._LOGOUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHSERVICE)

DESCRIPTOR.services_by_name['AuthService'] = _AUTHSERVICE

# @@protoc_insertion_point(module_scope)
