version: "3.8"
services: 
  auth_svc:
    build: .
    depends_on: 
      - database_svc
      - session_svc
    environment: 
      PORT: ':9091'
      WORKERS: '1'
      DB_HOST: 'database_svc'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_NAME: 'db'
      REDIS_HOST: 'session_svc'
      REDIS_PORT: '6379'
      REDIS_MAX_CON: '10'
    ports: 
      - "9091:9091"
  database_svc:
    # Connect to db: docker exec <container name> bash
    #                $ mysql -u <user> -p -h127.0.0.1
    #                $ <password>
    image: mysql
    volumes: 
      - ./_test_db_data:/var/lib/mysql
      - ./database/initialization:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_DATABASE: 'db'
    cap_add:
      - SYS_NICE  # More magic
  session_svc:
    image: redis
  