version: "3.8"
services:
  client_svc:
    build: services/Client
    ports:
      - "80:80"
  proxy_svc:
    build: services/Proxy
    ports:
      - "8080:8080"
  api_svc:
    build: services/ApiService
    environment: 
      - PORT=:9090
    ports:
      - "9090:9090"
  auth_svc:
    build: services/Auth
    ports:
      - "9091:9091"
  shortcut_svc:
    build: services/Shortcut
    ports:
      - "9092:9092"
  user_svc:
    build: services/User
    ports:
      - "9093:9093"
  database_svc:
    image: mysql
    command: --default-authentication-plug=mysql_native_password
    restart: always
    env_file: ./services/Database/database.env
      
    