version: "3.8"
services:
  # client_svc:
  #   build: services/Client
  #   depends_on: 
  #     - proxy_svc
  #   ports:
  #     - "80:80"
  proxy_svc:
    build: services/Proxy
    depends_on: 
      - api_svc
    ports:
      - "8080:8080"
  api_svc:
    build: services/ApiService
    depends_on: 
      - auth_svc
      - shortcut_svc
      - user_svc
    environment: 
      PORT: '9090'
      AUTH_ADDR: 'auth_svc:9091'
      SHORTCUT_ADDR: 'shorcut_svc:9092'
      USER_ADDR: 'user_svc:9093'
    ports:
      - "9090:9090"
  auth_svc:
    build: services/AuthService
    depends_on: 
      - database_svc
      - session_svc
    environment: 
      PORT: ':9091'
      WORKERS: '1'
      DB_HOST: 'database_svc'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_NAME: 'db'
      REDIS_HOST: 'session_svc'
      REDIS_PORT: '6379'
      REDIS_MAX_CON: '10'
  shortcut_svc:
    build: services/ShortcutService
    depends_on: 
      - database_svc
    environment: 
      PORT: ':9092'
  user_svc:
    build: services/UserService
    depends_on: 
      - database_svc
    ports: 
      - "9093:9093"
    environment: 
      PORT: '9093'
      DB_HOST: 'database_svc'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_NAME: 'db'
      DB_PORT: '3306'
  database_svc:
    # Connect to db: docker exec <container name> bash
    #                $ mysql -u <user> -p -h127.0.0.1
    #                $ <password>
    #command: "--socket=/tmp/mysql.sock" # something to do with windows idk
    image: mysql
    volumes: 
      - ./_test_db_data:/var/lib/mysql
      - ./database/initialization:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: 'root' # TODO: load these from ignored .env file
      MYSQL_DATABASE: 'db'
    cap_add:
      - SYS_NICE  # More magic
  session_svc:
    image: redis
      
    