version: "3.8"
services:
  # client_svc:
  #   build: services/Client
  #   depends_on: 
  #     - proxy_svc
  #   ports:
  #     - "80:80"
  # proxy_svc:
  #   build: services/Proxy
  #   depends_on: 
  #     - api_svc
  #   ports:
  #     - "8080:8080"
  api_svc:
    build: services/ApiService
    depends_on: 
      - auth_svc
      #- shortcut_svc
      #- user_svc
    environment: 
      - PORT=:9090
    ports:
      - "9090:9090"
  auth_svc:
    build: services/AuthService
    depends_on: 
      - database_svc
      - session_svc
    environment: 
      PORT: '9091'
      WORKERS: '3'
      DB_HOST: 'database_svc'
      DB_USER: 'root'
      DB_PASS: 'password'
      DB_NAME: 'db'
      REDIS_HOST: 'session_svc'
      REDIS_PORT: '6379'
      REDIS_MAX_CON: '10'
  # shortcut_svc:
  #   build: services/Shortcut
  #   depends_on: 
  #     - database_svc
  # user_svc:
  #   build: services/User
  #   depends_on: 
  #     - database_svc
  database_svc:
    # Connect to db: docker exec <container name> bash
    #                $ mysql -u <user> -p -h127.0.0.1
    #                $ <password>
    image: mysql/mysql-server:latest
    command: "--socket=/tmp/mysql.sock" # something to do with windows idk
    volumes: 
      - ./_test_db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 'password' # TODO: load these from ignored .env file
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
  session_svc:
    image: redis
      
    